### ISSUE TITLE
Tags for releases?

### ISSUE THREAD

**Issue by bollwyvl** [soul-catcher/mypy-gitlab-code-quality#15]
Hello, and thanks for this tool.

Would it be possible to add tags for releases that end up on pypi? This would be useful for tracking changes downstream, especially to any future dependency/python version changes.

Motivation: https://github.com/conda-forge/mypy-gitlab-code-quality-feedstock/pull/1

**Comment by soul-catcher** [comment]
Thank you for suggestion!

Could you clarify which tags you mean?

**Comment by bollwyvl** [comment]
Sure:  when reviewing that PR above, it would have been nice if i could have gone to:

https://github.com/soul-catcher/mypy-gitlab-code-quality/tags

And seen a tag for:

https://github.com/soul-catcher/mypy-gitlab-code-quality/tags/v1.1.0

And compared it with the previous release:

https://github.com/soul-catcher/mypy-gitlab-code-quality/compare/v1.0.0...v1.1.0

**Comment by soul-catcher** [comment]
I just pushed tags for three last releases and seems comparison between releases now worked.

This is my first open source project that got some popularity and I really appreciate pull requests and suggestions like this one!
